# Generated by Django 4.2.5 on 2023-09-27 12:25

from django.db import migrations, models
import robots.validator


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='model',
            field=models.CharField(max_length=2, validators=[robots.validator.validate_robot_data]),
        ),
    ]
