# Generated by Django 4.2.5 on 2023-09-28 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_alter_robot_model'),
        ('robots', '0003_alter_robot_created'),
    ]

    operations = [
    ]
